---
title: "ML project"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
Load required packages
```{r}
install.packages("proxy")
install.packages("devtools")
install.packages("stream")
install.packages("ff")

library(proxy)
library(devtools)
library(stream)
library(ff)
require(proxy)
require(devtools)
require(stream)
require(ff)
```

1. Load data Glass
```{R}
library(e1071)
library(rpart)
data(Glass, package="mlbench")

# w = table(Glass$Type)
# t = as.data.frame(w)
# t
#Glass[with(Glass, order(Type)), ]
Glass<-Glass[(Glass$Type ==2 | Glass$Type==6),]
## split data into a train and test set
index <- 1:nrow(Glass)
testindex <- sample(index, trunc(length(index)/2))
testset <- Glass[testindex,]
trainset <- Glass[-testindex,]
```

2* Resampling SMOTE - Glass
```{r}
library(smotefamily)
library(DMwR)
trainset$Type <- as.factor(trainset$Type)
trainset <- SMOTE(Type ~ ., trainset, perc.over = 2000, perc.under=105)
trainset$Type <- as.numeric(trainset$Type)
prop.table(table(trainset$Type))

```


4.. SVM -- Glass
```{R}
library(pROC)
testset$Type <- as.numeric(testset$Type)

## svm
svm.model <- svm(Type ~ ., data = trainset, cost = 100, gamma = 1)
svm.pred <- predict(svm.model, testset[,-10])

## compute svm confusion matrix
table(pred = svm.pred, true = testset[,10])

## plot AUC curve
auc <- roc(testset$Type, svm.pred)
print(auc)

plot(auc, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc$auc[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)

```

1.1. Simulate Streaming
```{R}
##randomize and group
trainset <- trainset[sample(nrow(trainset)),]
Tindex <- 1:nrow(trainset)
##Ttestindex <- sample(Tindex, trunc(length(Tindex)/5))
group1 <- trainset[1:4,]
group2 <- trainset[5:8,]
group3 <- trainset[9:12,]
group4 <- trainset[13:16,]
group5 <- trainset[17:20,]
group6 <- trainset[21:24,]
group7 <- trainset[25:28,]
group8 <- trainset[29:32,]
group9 <- trainset[33:36,]
group10 <- trainset[37:43,]
```

1.2 SMOTE-1
```{R}
##SMOTE
library(smotefamily)
library(DMwR)
group1$Type <- as.factor(group1$Type)
group1 <- SMOTE(Type ~ ., group1, perc.over = 2000, perc.under=105)
group1$Type <- as.numeric(group1$Type)
prop.table(table(group1$Type))
```

```{R}
group2$Type <- as.factor(group2$Type)
group2 <- SMOTE(Type ~ ., group2, perc.over = 2000, perc.under=105)
group2$Type <- as.numeric(group2$Type)
prop.table(table(group2$Type))
```

```{R}
group3$Type <- as.factor(group3$Type)
group3 <- SMOTE(Type ~ ., group3, perc.over = 2000, perc.under=105)
group3$Type <- as.numeric(group3$Type)
prop.table(table(group3$Type))
```

```{R}
group4$Type <- as.factor(group4$Type)
group4 <- SMOTE(Type ~ ., group4, perc.over = 2000, perc.under=105)
group4$Type <- as.numeric(group4$Type)
prop.table(table(group4$Type))
```

```{R}
group5$Type <- as.factor(group5$Type)
group5 <- SMOTE(Type ~ ., group5, perc.over = 2000, perc.under=105)
group5$Type <- as.numeric(group5$Type)
prop.table(table(group5$Type))
```

```{R}
group6$Type <- as.factor(group6$Type)
group6 <- SMOTE(Type ~ ., group6, perc.over = 2000, perc.under=105)
group6$Type <- as.numeric(group6$Type)
prop.table(table(group6$Type))
```

```{R}
group7$Type <- as.factor(group7$Type)
group7 <- SMOTE(Type ~ ., group7, perc.over = 2000, perc.under=105)
group7$Type <- as.numeric(group7$Type)
prop.table(table(group7$Type))
```

```{R}
group8$Type <- as.factor(group8$Type)
group8 <- SMOTE(Type ~ ., group8, perc.over = 2000, perc.under=105)
group8$Type <- as.numeric(group8$Type)
prop.table(table(group8$Type))
```

```{R}
group9$Type <- as.factor(group9$Type)
group9 <- SMOTE(Type ~ ., group9, perc.over = 2000, perc.under=105)
group9$Type <- as.numeric(group9$Type)
prop.table(table(group9$Type))
```

```{R}
group10$Type <- as.factor(group10$Type)
group10 <- SMOTE(Type ~ ., group10, perc.over = 2000, perc.under=105)
group10$Type <- as.numeric(group10$Type)
prop.table(table(group10$Type))
```

1.3 SVM
```{R}
library(pROC)
testset$Type <- as.numeric(testset$Type)

## svm
svm.model1 <- svm(Type ~ ., data = group1, cost = 100, gamma = 1)
svm.pred1 <- predict(svm.model1, testset[,-10])

## compute svm confusion matrix
table(pred1 = svm.pred1, true = testset[,10])

## plot AUC curve
auc1 <- roc(testset$Type, svm.pred1)
print(auc1)

plot(auc1, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc1$auc1[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model2 <- svm(Type ~ ., data = group2, cost = 100, gamma = 1)
svm.pred2 <- predict(svm.model2, testset[,-10])

## compute svm confusion matrix
table(pred2 = svm.pred2, true = testset[,10])

## plot AUC curve
auc2 <- roc(testset$Type, svm.pred2)
print(auc2)

plot(auc2, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc2$auc2[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model3 <- svm(Type ~ ., data = group3, cost = 100, gamma = 1)
svm.pred3 <- predict(svm.model3, testset[,-10])

## compute svm confusion matrix
table(pred3 = svm.pred3, true = testset[,10])

## plot AUC curve
auc3 <- roc(testset$Type, svm.pred3)
print(auc3)

plot(auc3, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc3$auc3[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model4 <- svm(Type ~ ., data = group4, cost = 100, gamma = 1)
svm.pred4 <- predict(svm.model4, testset[,-10])

## compute svm confusion matrix
table(pred4 = svm.pred4, true = testset[,10])

## plot AUC curve
auc4 <- roc(testset$Type, svm.pred4)
print(auc4)

plot(auc4, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc4$auc4[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model5 <- svm(Type ~ ., data = group5, cost = 100, gamma = 1)
svm.pred5 <- predict(svm.model5, testset[,-10])

## compute svm confusion matrix
table(pred5 = svm.pred5, true = testset[,10])

## plot AUC curve
auc5 <- roc(testset$Type, svm.pred5)
print(auc5)

plot(auc5, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc5$auc5[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model6 <- svm(Type ~ ., data = group6, cost = 100, gamma = 1)
svm.pred6 <- predict(svm.model6, testset[,-10])

## compute svm confusion matrix
table(pred6 = svm.pred6, true = testset[,10])

## plot AUC curve
auc6 <- roc(testset$Type, svm.pred6)
print(auc6)

plot(auc6, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc6$auc6[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model7 <- svm(Type ~ ., data = group7, cost = 100, gamma = 1)
svm.pred7 <- predict(svm.model7, testset[,-10])

## compute svm confusion matrix
table(pred7 = svm.pred7, true = testset[,10])

## plot AUC curve
auc7 <- roc(testset$Type, svm.pred7)
print(auc7)

plot(auc7, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc7$auc7[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model8 <- svm(Type ~ ., data = group8, cost = 100, gamma = 1)
svm.pred8 <- predict(svm.model8, testset[,-10])

## compute svm confusion matrix
table(pred8 = svm.pred8, true = testset[,10])

## plot AUC curve
auc8 <- roc(testset$Type, svm.pred8)
print(auc8)

plot(auc8, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc8$auc8[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model9 <- svm(Type ~ ., data = group9, cost = 100, gamma = 1)
svm.pred9 <- predict(svm.model9, testset[,-10])

## compute svm confusion matrix
table(pred9 = svm.pred9, true = testset[,10])

## plot AUC curve
auc9 <- roc(testset$Type, svm.pred9)
print(auc9)

plot(auc9, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc9$auc9[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

```{R}
testset$Type <- as.numeric(testset$Type)

## svm
svm.model10 <- svm(Type ~ ., data = group10, cost = 100, gamma = 1)
svm.pred10 <- predict(svm.model10, testset[,-10])

## compute svm confusion matrix
table(pred10 = svm.pred10, true = testset[,10])

## plot AUC curve
auc10 <- roc(testset$Type, svm.pred10)
print(auc10)

plot(auc10, ylim=c(0,1), print.thres=TRUE, main=paste('AUC:',round(auc10$auc10[[1]],2)))
abline(h=1,col='blue',lwd=2)
abline(h=0,col='red',lwd=2)
```

1* Load data Ozone
```{R}
data(Ozone, package="mlbench")
#Ozone[with(Ozone, order(V4)), ]

Ozone1 <- subset(Ozone, V4 == 3)
Ozone2 <- subset(Ozone, V4 == 34)

Ozone <- rbind(Ozone1,Ozone2)

#Ozone<-Ozone[(Ozone$V4 == 3 | Ozone$V4 == 34),]
## split data into a train and test set
index <- 1:nrow(Ozone)
testindex <- sample(index, trunc(length(index)/3))
testset <- na.omit(Ozone[testindex,-3])
trainset <- na.omit(Ozone[-testindex,-3])
```

**SVM
```{R}
library(pROC)
 ## svm
testset$Type <- as.numeric(testset$Type)
svm.model <- svm(V4 ~ ., data = trainset, cost = 100, gamma = 1)
svm.pred <- predict(svm.model, testset[,-3])
crossprod(svm.pred - testset[,3]) / length(testindex)
table(pred = svm.pred, true = testset[,3])
auc <- roc(testset$Type, svm.pred)
print(auc)

```

2.Resampling - SMOTE
```{r}
library(smotefamily)
newOzone <- SMOTE(V4 ~ ., data = Ozone, perc.over=5, k=2, learner=NULL)
table(newOzone$V4)

par(mfrow = c(1, 2))
plot(data[, 1], data[, 2], pch = 19 + as.integer(Ozone[, 3]),
     main = "Original Data")
plot(newOzone[, 1], newOzone[, 2], pch = 19 + as.integer(newOzone[,3]),
     main = "SMOTE'd Data")

classTree <- SMOTE(V4 ~ ., Ozone, perc.over = 600,perc.under=100,
                   learner='rpartXse',se=0.5)
```




2. Load data from UCI as streams
```{r}
library(e1071)
library(tidyr)
sick_data <- read.table("http://mlearn.ics.uci.edu/databases/thyroid-disease/sick.data", sep = ",")
sick_test <- read.table("http://mlearn.ics.uci.edu/databases/thyroid-disease/sick.test", sep = ",")
sick_data <- separate(data = sick_data, col = V30, into = c("V30", "V31"))
sick_test <- separate(data = sick_test, col = V30, into = c("V30", "V31"))
sick_data$V31 <- NULL
sick_test$V31 <-NULL
sick_data$V28 <- NULL
sick_test$V28 <-NULL
l <- sapply(sick_data, function(x) is.factor(x))
m <- sick_data[, l]
ifelse(n <- sapply(m, function(x) length(levels(x))) == 1, "DROP", "NODROP")
## svm
svm.model <- svm(V30 ~ ., sick_data, cost = 100, gamma = 1)
svm.pred <- predict(svm.model, sick_test[,-30])

## compute svm confusion matrix
table(pred = svm.pred, true = sick_test[,30])
```

```{R}
## A small example with a data set created artificially from the IRIS
## data 
data(iris)
data <- iris[, c(1, 2, 5)]
data$Species <- factor(ifelse(data$Species == "setosa","rare","common")) 
## checking the class distribution of this artificial data set
table(data$Species)

## now using SMOTE to create a more "balanced problem"
newData <- SMOTE(Species ~ ., data, perc.over = 600,perc.under=100)
table(newData$Species)

## Checking visually the created data
## Not run: 
par(mfrow = c(1, 2))
plot(data[, 1], data[, 2], pch = 19 + as.integer(data[, 3]),
     main = "Original Data")
plot(newData[, 1], newData[, 2], pch = 19 + as.integer(newData[,3]),
     main = "SMOTE'd Data")

## End(Not run)

## Now an example where we obtain a model with the "balanced" data
classTree <- SMOTE(Species ~ ., data, perc.over = 600,perc.under=100,
                   learner='rpartXse',se=0.5)
## check the resulting classification tree
classTree
## The tree with the unbalanced data set would be
rpartXse(Species ~ .,data,se=0.5)
```
